---
- name: folder permission
#  debug: msg='{{item}}'
  file:
    path: '{{item}}'
    state: directory
    owner: '{{mysqlosuser}}'
    group: '{{mysqlosuser}}'
  become: true
  with_items:
    - '{{datapath}}'
    - '{{logpath}}'
- name: copy configuration parameter
  template:
    src: my.cnf.standAlone.j2
    dest: /etc/my.cnf
#  notify: restart mongod
  become: true
- name: tuning open file limits. Caution! - this is useless for systemd
  pam_limits:
    domain: '{{mysqlosuser}}'
    limit_item: nofile
    limit_type: soft
    value: '{{nofilelimit}}'
  become: true
- name: tuning open file limits for systemd
  template:
    src: mysqld.service.j2
    dest: /usr/lib/systemd/system/mysqld.service
  become: true
# SELinux 사용시 너무 불편해서 일단 뺌
# selinux의 policy를 설정하기 위해서는 policycoreutils-python 가 설치되어 있어야 한다고 나옴. common role에 넣어야 할 듯.
#- name: install policycoreutils-python for SELinux
#  yum:
#    name: policycoreutils-python
#    state: present
#  become: true

# CentOS는 SELinux가 enable되어 있다고 함. logpath와 datapath에 대해서 mongod가 사용할 수 있도록 file context를 수정해야 함
#chcon -Rv --type=mongod_log_t /data0/mongodb
#ls -Z 를 했을 때 이렇게 나오면 됨. unconfined_u:object_r:mongod_log_t:s0
#- name: enable log folder writable by mongod
#  shell: 'chcon -Rv --type=mysqld_log_t {{logpath}}'
#  register: chcon_logpath_result
#  become: true
#  changed_when: chcon_logpath_result.rc != 0
# 아래처럼 module을 쓰고 싶은데 안되네..
#  sefcontext:
#    target: '{{logpath}}'
#    setype: mongod_log_t
#    seuser: unconfined_u
#    selevel: s0
#    state: present
#chcon -Rv --type=mongod_var_lib_t /data1/mongo/
#- name: enable db folder writable by mongod
#  shell: 'chcon -Rv --type=mysqld_db_t {{datapath}}'
#  register: chcon_datapath_result
#  become: true
#  changed_when: chcon_datapath_result.rc != 0
#  sefcontext:
#    target: '{{datapath}}'
#    setype: mongod_var_lib_t
#    seuser: unconfined_u
#    selevel: s0
#    state: present